In [1]:
import lasio

In [8]:
las_file_path = 'Data/LAS/Barossa-6_24hrs Time Ascii_010517.LAS'

wellTime1 = lasio.read(las_file_path)

print("\nData:")

df1=wellTime1.df()
df1.head()

df1.tail()

Data:

,BIT DEPTH,TOTAL DEPTH,LAGGED TOTAL DEPTH,HOOK HEIGHT,WEIGHT ON HOOK,WEIGHT ON BIT DRILLER,WEIGHT ON HOOK MIN,WEIGHT ON HOOK MAX,SURFACE TORQUE MIN,SURFACE TORQUE MAX,...,H2S @ RIG FLOOR,H2S OUT,TOTAL GAS OUT 1,C1 OUT 1,C2 OUT 1,C3 OUT 1,IC4 OUT 1,NC4 OUT 1,IC5 OUT 1,NC5 OUT 1
ETIM,,,,,,,,,,,,,,,,,,,,,
75.0,2313.91,2378.88,2378.87,12.11,107.94,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0358,122.0,3.0,1.0,4.0,0.0,15.0,0.0
80.0,2313.91,2378.88,2378.87,12.11,107.94,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0357,122.0,3.0,1.0,4.0,0.0,15.0,0.0
85.0,2313.91,2378.88,2378.87,12.11,107.39,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0360,122.0,3.0,1.0,4.0,0.0,15.0,0.0
90.0,2313.91,2378.88,2378.87,12.11,107.39,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0361,123.0,3.0,1.0,4.0,0.0,15.0,0.0
95.0,2313.91,2378.88,2378.87,12.11,107.94,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0360,123.0,3.0,1.0,4.0,0.0,15.0,0.0

In [7]:
import os

print("Working directory:", os.getcwd())

Working directory: C:\Users\peter\Documents\dataanalytics

In [6]:
os.chdir('C:\\Users\\peter\\Documents\\dataanalytics')