In [15]:
import lasio
import pandas as pd

In [6]:
las_file_path = 'Data/LAS/Barossa-6_24hrs Time Ascii_010517.LAS'

In [9]:
wellTime1 = lasio.read(las_file_path)

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'Data/LAS/Barossa-6_24hrs Time Ascii_010517.LAS'

In [10]:
os.getcwd()

'C:\\Users\\peter\\Documents\\dataanalytics\\Day1'

In [11]:
os.chdir('C:\\Users\\peter\\Documents\\dataanalytics')

In [12]:
os.getcwd()

'C:\\Users\\peter\\Documents\\dataanalytics'

In [13]:
wellTime1 = lasio.read(las_file_path)

In [17]:
df1 = wellTime1.df()
df1.head()

,BIT DEPTH,TOTAL DEPTH,LAGGED TOTAL DEPTH,HOOK HEIGHT,WEIGHT ON HOOK,WEIGHT ON BIT DRILLER,WEIGHT ON HOOK MIN,WEIGHT ON HOOK MAX,SURFACE TORQUE MIN,SURFACE TORQUE MAX,...,H2S @ RIG FLOOR,H2S OUT,TOTAL GAS OUT 1,C1 OUT 1,C2 OUT 1,C3 OUT 1,IC4 OUT 1,NC4 OUT 1,IC5 OUT 1,NC5 OUT 1
ETIM,,,,,,,,,,,,,,,,,,,,,
0.0,2256.53,NaN,2267.82,42.26,313.47,3.90,313.49,313.49,1980.76,1980.76,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5.0,2256.57,NaN,2267.82,42.22,314.46,3.12,314.88,314.88,1980.69,1980.69,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10.0,2256.64,NaN,2267.82,42.16,313.43,4.56,313.28,313.28,2018.69,2018.69,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15.0,2256.66,NaN,2267.82,42.14,316.84,0.34,317.19,317.19,2052.03,2052.03,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20.0,2256.70,NaN,2267.82,42.10,316.50,0.56,317.05,317.05,1980.59,1980.59,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df1.head(10)

,BIT DEPTH,TOTAL DEPTH,LAGGED TOTAL DEPTH,HOOK HEIGHT,WEIGHT ON HOOK,WEIGHT ON BIT DRILLER,WEIGHT ON HOOK MIN,WEIGHT ON HOOK MAX,SURFACE TORQUE MIN,SURFACE TORQUE MAX,...,H2S @ RIG FLOOR,H2S OUT,TOTAL GAS OUT 1,C1 OUT 1,C2 OUT 1,C3 OUT 1,IC4 OUT 1,NC4 OUT 1,IC5 OUT 1,NC5 OUT 1
ETIM,,,,,,,,,,,,,,,,,,,,,
0.0,2256.53,NaN,2267.82,42.26,313.47,3.90,313.49,313.49,1980.76,1980.76,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5.0,2256.57,NaN,2267.82,42.22,314.46,3.12,314.88,314.88,1980.69,1980.69,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10.0,2256.64,NaN,2267.82,42.16,313.43,4.56,313.28,313.28,2018.69,2018.69,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15.0,2256.66,NaN,2267.82,42.14,316.84,0.34,317.19,317.19,2052.03,2052.03,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20.0,2256.70,NaN,2267.82,42.10,316.50,0.56,317.05,317.05,1980.59,1980.59,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25.0,2256.74,NaN,2267.82,42.05,314.78,3.25,314.67,314.67,2047.76,2047.76,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30.0,2256.78,NaN,2267.82,42.01,314.05,3.85,313.96,313.96,2036.95,2036.95,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35.0,2256.82,NaN,2267.82,41.97,313.85,3.96,313.85,313.85,2022.38,2022.38,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40.0,2256.85,NaN,2267.82,41.94,313.92,3.34,314.14,314.14,2037.56,2037.56,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45.0,2256.89,NaN,2267.82,41.91,316.43,1.42,316.83,316.83,2050.97,2050.97,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df1.tail(20)

,BIT DEPTH,TOTAL DEPTH,LAGGED TOTAL DEPTH,HOOK HEIGHT,WEIGHT ON HOOK,WEIGHT ON BIT DRILLER,WEIGHT ON HOOK MIN,WEIGHT ON HOOK MAX,SURFACE TORQUE MIN,SURFACE TORQUE MAX,...,H2S @ RIG FLOOR,H2S OUT,TOTAL GAS OUT 1,C1 OUT 1,C2 OUT 1,C3 OUT 1,IC4 OUT 1,NC4 OUT 1,IC5 OUT 1,NC5 OUT 1
ETIM,,,,,,,,,,,,,,,,,,,,,
0.0,2313.91,2378.88,2378.87,12.57,98.57,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0361,124.0,3.0,1.0,4.0,0.0,16.0,0.0
5.0,2313.91,2378.88,2378.87,12.32,98.57,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0360,124.0,3.0,1.0,4.0,0.0,16.0,0.0
10.0,2313.91,2378.88,2378.87,12.24,98.40,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0361,124.0,3.0,1.0,4.0,0.0,17.0,0.0
15.0,2313.91,2378.88,2378.87,12.22,100.22,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0360,124.0,3.0,1.0,4.0,0.0,16.0,0.0
20.0,2313.91,2378.88,2378.87,12.20,99.84,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0361,123.0,3.0,1.0,4.0,0.0,16.0,0.0
25.0,2313.91,2378.88,2378.87,12.19,101.88,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0360,123.0,3.0,1.0,4.0,0.0,16.0,0.0
30.0,2313.91,2378.88,2378.87,12.17,101.27,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0360,123.0,3.0,1.0,4.0,0.0,16.0,0.0
35.0,2313.91,2378.88,2378.87,12.16,101.71,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0362,123.0,3.0,1.0,4.0,0.0,16.0,0.0
40.0,2313.91,2378.88,2378.87,12.16,102.26,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0361,123.0,3.0,1.0,4.0,0.0,16.0,0.0
45.0,2313.91,2378.88,2378.87,12.15,102.43,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0365,122.0,3.0,1.0,4.0,0.0,16.0,0.0
50.0,2313.91,2378.88,2378.87,12.15,102.81,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0367,122.0,3.0,1.0,4.0,0.0,16.0,0.0
55.0,2313.91,2378.88,2378.87,12.11,91.20,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0370,122.0,3.0,1.0,4.0,0.0,16.0,0.0
60.0,2313.91,2378.88,2378.87,12.11,103.80,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0369,122.0,3.0,1.0,4.0,0.0,15.0,0.0
65.0,2313.91,2378.88,2378.87,12.11,107.94,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0365,122.0,3.0,1.0,4.0,0.0,15.0,0.0
70.0,2313.91,2378.88,2378.87,12.11,107.94,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0361,122.0,3.0,1.0,4.0,0.0,15.0,0.0
75.0,2313.91,2378.88,2378.87,12.11,107.94,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0358,122.0,3.0,1.0,4.0,0.0,15.0,0.0
80.0,2313.91,2378.88,2378.87,12.11,107.94,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0357,122.0,3.0,1.0,4.0,0.0,15.0,0.0
85.0,2313.91,2378.88,2378.87,12.11,107.39,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0360,122.0,3.0,1.0,4.0,0.0,15.0,0.0
90.0,2313.91,2378.88,2378.87,12.11,107.39,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0361,123.0,3.0,1.0,4.0,0.0,15.0,0.0
95.0,2313.91,2378.88,2378.87,12.11,107.94,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0360,123.0,3.0,1.0,4.0,0.0,15.0,0.0

In [21]:
las_file_path = 'Data/Las/Barossa-6_24hrs Time Ascii_020517.LAS'
wellTime2 = lasio.read(las_file_path)
df2 = wellTime2.df()
df2.head()

,BIT DEPTH,TOTAL DEPTH,LAGGED TOTAL DEPTH,HOOK HEIGHT,WEIGHT ON HOOK,WEIGHT ON BIT DRILLER,WEIGHT ON HOOK MIN,WEIGHT ON HOOK MAX,SURFACE TORQUE MIN,SURFACE TORQUE MAX,...,H2S @ RIG FLOOR,H2S OUT,TOTAL GAS OUT 1,C1 OUT 1,C2 OUT 1,C3 OUT 1,IC4 OUT 1,NC4 OUT 1,IC5 OUT 1,NC5 OUT 1
ETIM,,,,,,,,,,,,,,,,,,,,,
0.0,2313.91,2378.88,2378.87,12.11,107.39,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0362,123.0,3.0,1.0,4.0,0.0,15.0,0.0
5.0,2313.91,2378.88,2378.87,12.11,107.39,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0361,123.0,3.0,1.0,4.0,0.0,15.0,0.0
10.0,2313.91,2378.88,2378.87,12.11,107.39,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0360,123.0,3.0,1.0,4.0,0.0,15.0,0.0
15.0,2313.91,2378.88,2378.87,12.11,107.39,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0360,123.0,3.0,1.0,4.0,0.0,15.0,0.0
20.0,2313.91,2378.88,2378.87,12.11,107.39,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0358,123.0,3.0,1.0,4.0,0.0,15.0,0.0

In [22]:
df3 = pd.concat([df1,df2])

In [23]:
df3.head()

,BIT DEPTH,TOTAL DEPTH,LAGGED TOTAL DEPTH,HOOK HEIGHT,WEIGHT ON HOOK,WEIGHT ON BIT DRILLER,WEIGHT ON HOOK MIN,WEIGHT ON HOOK MAX,SURFACE TORQUE MIN,SURFACE TORQUE MAX,...,H2S @ RIG FLOOR,H2S OUT,TOTAL GAS OUT 1,C1 OUT 1,C2 OUT 1,C3 OUT 1,IC4 OUT 1,NC4 OUT 1,IC5 OUT 1,NC5 OUT 1
ETIM,,,,,,,,,,,,,,,,,,,,,
0.0,2256.53,NaN,2267.82,42.26,313.47,3.90,313.49,313.49,1980.76,1980.76,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5.0,2256.57,NaN,2267.82,42.22,314.46,3.12,314.88,314.88,1980.69,1980.69,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10.0,2256.64,NaN,2267.82,42.16,313.43,4.56,313.28,313.28,2018.69,2018.69,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15.0,2256.66,NaN,2267.82,42.14,316.84,0.34,317.19,317.19,2052.03,2052.03,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20.0,2256.70,NaN,2267.82,42.10,316.50,0.56,317.05,317.05,1980.59,1980.59,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df3.tail()

,BIT DEPTH,TOTAL DEPTH,LAGGED TOTAL DEPTH,HOOK HEIGHT,WEIGHT ON HOOK,WEIGHT ON BIT DRILLER,WEIGHT ON HOOK MIN,WEIGHT ON HOOK MAX,SURFACE TORQUE MIN,SURFACE TORQUE MAX,...,H2S @ RIG FLOOR,H2S OUT,TOTAL GAS OUT 1,C1 OUT 1,C2 OUT 1,C3 OUT 1,IC4 OUT 1,NC4 OUT 1,IC5 OUT 1,NC5 OUT 1
ETIM,,,,,,,,,,,,,,,,,,,,,
75.0,2944.44,2944.44,2916.45,5.16,299.32,38.49,299.44,299.44,6890.67,6890.67,...,0.0,NaN,0.2092,1848.0,51.0,23.0,16.0,2.0,14.0,0.0
80.0,2944.47,2944.47,2916.51,5.13,298.93,39.20,298.85,298.85,6857.78,6857.78,...,0.0,NaN,0.2083,1842.0,51.0,23.0,16.0,2.0,14.0,0.0
85.0,2944.53,2944.53,2916.55,5.07,298.12,39.44,298.22,298.22,6694.24,6694.24,...,0.0,NaN,0.2075,1837.0,51.0,23.0,16.0,2.0,14.0,0.0
90.0,2944.57,2944.57,2916.56,5.03,298.28,39.21,298.51,298.51,6789.10,6789.10,...,0.0,NaN,0.2077,1831.0,50.0,22.0,16.0,2.0,14.0,0.0
95.0,2944.60,2944.60,2916.64,5.00,299.56,38.22,299.70,299.70,6930.75,6930.75,...,0.0,NaN,0.2072,1826.0,50.0,22.0,16.0,2.0,14.0,0.0

In [28]:
df3.head(10).equals(df1.head(10))

True

In [26]:
type(df1.head())

pandas.core.frame.DataFrame

In [27]:
df3.equals(df1)

False

In [29]:
df3.tail().equals(df2.tail())

True

In [30]:
len(df1)

17280

In [31]:
len(df2)

17280

In [32]:
len(df3)

34560

In [33]:
df1.tail(40)

,BIT DEPTH,TOTAL DEPTH,LAGGED TOTAL DEPTH,HOOK HEIGHT,WEIGHT ON HOOK,WEIGHT ON BIT DRILLER,WEIGHT ON HOOK MIN,WEIGHT ON HOOK MAX,SURFACE TORQUE MIN,SURFACE TORQUE MAX,...,H2S @ RIG FLOOR,H2S OUT,TOTAL GAS OUT 1,C1 OUT 1,C2 OUT 1,C3 OUT 1,IC4 OUT 1,NC4 OUT 1,IC5 OUT 1,NC5 OUT 1
ETIM,,,,,,,,,,,,,,,,,,,,,
0.0,2313.91,2378.88,2378.87,13.78,99.89,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0361,123.0,3.0,1.0,4.0,0.0,16.0,0.0
5.0,2313.91,2378.88,2378.87,13.78,102.81,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0359,123.0,3.0,1.0,4.0,0.0,16.0,0.0
10.0,2313.91,2378.88,2378.87,13.78,102.43,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0367,122.0,3.0,1.0,4.0,0.0,16.0,0.0
15.0,2313.91,2378.88,2378.87,13.78,102.98,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0366,122.0,3.0,1.0,4.0,0.0,16.0,0.0
20.0,2313.91,2378.88,2378.87,13.78,102.98,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0363,122.0,3.0,1.0,4.0,0.0,16.0,0.0
25.0,2313.91,2378.88,2378.87,13.78,102.98,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0360,122.0,3.0,1.0,4.0,0.0,16.0,0.0
30.0,2313.91,2378.88,2378.87,13.78,102.98,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0360,122.0,3.0,1.0,4.0,0.0,15.0,0.0
35.0,2313.91,2378.88,2378.87,13.78,102.98,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0357,122.0,3.0,1.0,4.0,0.0,15.0,0.0
40.0,2313.91,2378.88,2378.87,13.77,99.84,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0360,123.0,3.0,1.0,4.0,0.0,15.0,0.0
45.0,2313.91,2378.88,2378.87,13.76,102.09,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0357,123.0,3.0,1.0,4.0,0.0,15.0,0.0
50.0,2313.91,2378.88,2378.87,13.76,104.08,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0358,123.0,3.0,1.0,4.0,0.0,15.0,0.0
55.0,2313.91,2378.88,2378.87,13.76,103.53,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0368,123.0,3.0,1.0,4.0,0.0,15.0,0.0
60.0,2313.91,2378.88,2378.87,13.76,103.53,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0368,123.0,3.0,1.0,4.0,0.0,15.0,0.0
65.0,2313.91,2378.88,2378.87,13.76,103.53,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0364,123.0,3.0,1.0,4.0,0.0,15.0,0.0
70.0,2313.91,2378.88,2378.87,13.76,103.53,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0364,123.0,3.0,1.0,4.0,0.0,15.0,0.0
75.0,2313.91,2378.88,2378.87,13.76,103.53,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0362,123.0,3.0,1.0,4.0,0.0,15.0,0.0
80.0,2313.91,2378.88,2378.87,13.76,103.53,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0360,123.0,3.0,1.0,4.0,0.0,15.0,0.0
85.0,2313.91,2378.88,2378.87,13.75,103.53,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0359,123.0,3.0,1.0,4.0,0.0,16.0,0.0
90.0,2313.91,2378.88,2378.87,13.41,99.29,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0359,124.0,3.0,1.0,4.0,0.0,16.0,0.0
95.0,2313.91,2378.88,2378.87,12.87,98.02,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0358,124.0,3.0,1.0,4.0,0.0,16.0,0.0
0.0,2313.91,2378.88,2378.87,12.57,98.57,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0361,124.0,3.0,1.0,4.0,0.0,16.0,0.0
5.0,2313.91,2378.88,2378.87,12.32,98.57,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0360,124.0,3.0,1.0,4.0,0.0,16.0,0.0
10.0,2313.91,2378.88,2378.87,12.24,98.40,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0361,124.0,3.0,1.0,4.0,0.0,17.0,0.0
15.0,2313.91,2378.88,2378.87,12.22,100.22,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0360,124.0,3.0,1.0,4.0,0.0,16.0,0.0
20.0,2313.91,2378.88,2378.87,12.20,99.84,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0361,123.0,3.0,1.0,4.0,0.0,16.0,0.0
25.0,2313.91,2378.88,2378.87,12.19,101.88,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0360,123.0,3.0,1.0,4.0,0.0,16.0,0.0
30.0,2313.91,2378.88,2378.87,12.17,101.27,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0360,123.0,3.0,1.0,4.0,0.0,16.0,0.0
35.0,2313.91,2378.88,2378.87,12.16,101.71,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0362,123.0,3.0,1.0,4.0,0.0,16.0,0.0
40.0,2313.91,2378.88,2378.87,12.16,102.26,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0361,123.0,3.0,1.0,4.0,0.0,16.0,0.0
45.0,2313.91,2378.88,2378.87,12.15,102.43,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0365,122.0,3.0,1.0,4.0,0.0,16.0,0.0
50.0,2313.91,2378.88,2378.87,12.15,102.81,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0367,122.0,3.0,1.0,4.0,0.0,16.0,0.0
55.0,2313.91,2378.88,2378.87,12.11,91.20,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0370,122.0,3.0,1.0,4.0,0.0,16.0,0.0
60.0,2313.91,2378.88,2378.87,12.11,103.80,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0369,122.0,3.0,1.0,4.0,0.0,15.0,0.0
65.0,2313.91,2378.88,2378.87,12.11,107.94,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0365,122.0,3.0,1.0,4.0,0.0,15.0,0.0
70.0,2313.91,2378.88,2378.87,12.11,107.94,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0361,122.0,3.0,1.0,4.0,0.0,15.0,0.0
75.0,2313.91,2378.88,2378.87,12.11,107.94,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0358,122.0,3.0,1.0,4.0,0.0,15.0,0.0
80.0,2313.91,2378.88,2378.87,12.11,107.94,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0357,122.0,3.0,1.0,4.0,0.0,15.0,0.0
85.0,2313.91,2378.88,2378.87,12.11,107.39,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0360,122.0,3.0,1.0,4.0,0.0,15.0,0.0
90.0,2313.91,2378.88,2378.87,12.11,107.39,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0361,123.0,3.0,1.0,4.0,0.0,15.0,0.0
95.0,2313.91,2378.88,2378.87,12.11,107.94,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0360,123.0,3.0,1.0,4.0,0.0,15.0,0.0

In [34]:
df_reset = df3.reset_index()
df_reset.tail()

,ETIM,BIT DEPTH,TOTAL DEPTH,LAGGED TOTAL DEPTH,HOOK HEIGHT,WEIGHT ON HOOK,WEIGHT ON BIT DRILLER,WEIGHT ON HOOK MIN,WEIGHT ON HOOK MAX,SURFACE TORQUE MIN,...,H2S @ RIG FLOOR,H2S OUT,TOTAL GAS OUT 1,C1 OUT 1,C2 OUT 1,C3 OUT 1,IC4 OUT 1,NC4 OUT 1,IC5 OUT 1,NC5 OUT 1
34555,75.0,2944.44,2944.44,2916.45,5.16,299.32,38.49,299.44,299.44,6890.67,...,0.0,NaN,0.2092,1848.0,51.0,23.0,16.0,2.0,14.0,0.0
34556,80.0,2944.47,2944.47,2916.51,5.13,298.93,39.20,298.85,298.85,6857.78,...,0.0,NaN,0.2083,1842.0,51.0,23.0,16.0,2.0,14.0,0.0
34557,85.0,2944.53,2944.53,2916.55,5.07,298.12,39.44,298.22,298.22,6694.24,...,0.0,NaN,0.2075,1837.0,51.0,23.0,16.0,2.0,14.0,0.0
34558,90.0,2944.57,2944.57,2916.56,5.03,298.28,39.21,298.51,298.51,6789.10,...,0.0,NaN,0.2077,1831.0,50.0,22.0,16.0,2.0,14.0,0.0
34559,95.0,2944.60,2944.60,2916.64,5.00,299.56,38.22,299.70,299.70,6930.75,...,0.0,NaN,0.2072,1826.0,50.0,22.0,16.0,2.0,14.0,0.0

In [37]:
df_reset['ETIM'][-200:].plot(kind='line',marker='o',linestyle='-',color='blue')

In [39]:
plt.show()

In [40]:
data = {
    'Depth': [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000],
    'ROP' : [45, 55, 60, 40, 70, 30, 80, 20, 90, 25]
}

df = pd.DataFrame(data)

In [41]:
df.head()

   Depth  ROP
0    100   45
1    200   55
2    300   60
3    400   40
4    500   70

In [42]:
groups = df.groupby(df['ROP']>50)

In [43]:
groups

In [44]:
for name,group in groups:
    print(f"Group name: {name}")
    print(group)

Group name: False
   Depth  ROP
0    100   45
3    400   40
5    600   30
7    800   20
9   1000   25
Group name: True
   Depth  ROP
1    200   55
2    300   60
4    500   70
6    700   80
8    900   90

In [45]:
from bs4 import BeautifulSoup

In [50]:
WITSML_file = "Data\\WITSML\\1-2.xml"
with open(WITSML_file) as f:
    print(type(f))
    data = f.read()

<class '_io.TextIOWrapper'>

In [48]:
type(data)

str

In [51]:
data_xml = BeautifulSoup(data,'xml')

In [55]:
tags = set([str(tag.name) for tag in data_xml.find_all()])

In [57]:
type(tags)

set

In [59]:
print("\n".join(tags))

propAv
gasPeak
ibutAv
nbutMn
relatedLog
methAv
npentMx
rpmAv
ecdTdAv
methMn
type
ropMn
name
lithology
wobAv
ipentMx
commonData
ethMx
ipentAv
priv_ipLastChange
priv_userOwner
priv_ipOwner
dTimCreation
chromatograph
ibutMx
mudLog
ropMx
nameWell
mudGas
gasAv
lithPc
mudLogs
tqAv
dTim
mdBottom
endMd
priv_userLastChange
ethAv
npentAv
npentMn
ipentMn
typeLithology
nameWellbore
commonTime
nbutMx
methMx
ropAv
abundance
qualifier
gasBackgnd
wtMudAv
mudLogCompany
dxcAv
propMx
ibutMn
itemState
dTimLastChange
propMn
nbutAv
sourceName
priv_dTimReceived
codeLith
mdTop
startMd
geologyInterval
ethMn

In [61]:
tags_at_level = data_xml.find_all(lambda tag: len(tag.find_parents())==4)

In [86]:
tags_at_level = data_xml.find_all(lambda tag: len(tag.find_parents()) == 4)

df=pd.DataFrame()
ilitho=-1
row={}
for index,tag in enumerate(tags_at_level):
    if tag.name not in df.columns:
        df[tag.name]=0
    if tag.name=="typeLithology":
        ilitho+=1
        if ilitho:
            df=pd.concat([df,pd.DataFrame([row])],ignore_index=True)
            row={}
    try:
        row[tag.name]=float(tag.text)
    except:
        row[tag.name]=tag.text

In [87]:
df.head(10)

,typeLithology,mdTop,mdBottom,dTim,ropAv,ropMn,ropMx,wobAv,tqAv,rpmAv,...,mudGas,sourceName,dTimCreation,dTimLastChange,itemState,priv_userLastChange,priv_ipLastChange,priv_userOwner,priv_ipOwner,priv_dTimReceived
0,\n\t\t\t\tinterpreted\n\t\t\t,1380.1,1410.0,\n\t\t\t\t2013-11-10T22:49:01.000Z\n\t\t\t,0.005363,0.000400,0.001667,79490.036395,11037.087490,1.421590,...,0,0,0,0,0,0,0,0,0,0
1,\n\t\t\t\tcuttings\n\t\t\t,1410.0,1440.0,\n\t\t\t\t2013-11-10T22:49:01.000Z\n\t\t\t,0.007997,0.001624,0.002659,49199.723551,10937.664001,1.999623,...,\n\n\t\t\t\t\t2066\n\t\t\t\t\n\n\t\t\t\t\t2078...,0,0,0,0,0,0,0,0,0
2,\n\t\t\t\tcuttings\n\t\t\t,1410.0,1410.0,\n\t\t\t\t2013-11-28T22:05:13.000Z\n\t\t\t,NaN,NaN,NaN,NaN,NaN,NaN,...,\n\n\t\t\t\t\t2478\n\t\t\t\t\n\n\t\t\t\t\t2522...,0,0,0,0,0,0,0,0,0
3,\n\t\t\t\tinterpreted\n\t\t\t,1410.0,1440.0,\n\t\t\t\t2013-11-11T02:57:30.000Z\n\t\t\t,0.007997,0.001624,0.002659,49199.723551,10937.664001,1.999623,...,NaN,0,0,0,0,0,0,0,0,0
4,\n\t\t\t\tinterpreted\n\t\t\t,1440.0,1460.0,\n\t\t\t\t2013-11-14T03:54:59.000Z\n\t\t\t,0.007806,0.002668,0.003152,33501.490523,10582.888750,1.936630,...,NaN,0,0,0,0,0,0,0,0,0
5,\n\t\t\t\tcuttings\n\t\t\t,1440.0,1470.0,\n\t\t\t\t2013-11-11T02:11:47.000Z\n\t\t\t,0.008109,0.002668,0.003398,36392.208335,10908.709126,1.958701,...,\n\n\t\t\t\t\t2223\n\t\t\t\t\n\n\t\t\t\t\t4317...,0,0,0,0,0,0,0,0,0
6,\n\t\t\t\tinterpreted\n\t\t\t,1460.0,1500.0,\n\t\t\t\t2013-11-11T02:57:31.000Z\n\t\t\t,0.007935,0.003160,0.003910,38287.602536,11219.619751,1.998267,...,NaN,0,0,0,0,0,0,0,0,0
7,\n\t\t\t\tcuttings\n\t\t\t,1470.0,1500.0,\n\t\t\t\t2013-11-11T02:11:47.000Z\n\t\t\t,0.007676,0.003404,0.003910,37024.162808,11110.287915,1.997153,...,\n\n\t\t\t\t\t2722\n\t\t\t\t\n\n\t\t\t\t\t2981...,0,0,0,0,0,0,0,0,0
8,\n\t\t\t\tinterpreted\n\t\t\t,1500.0,1530.0,\n\t\t\t\t2013-11-11T03:35:05.000Z\n\t\t\t,0.007794,0.003916,0.004318,40566.284640,10469.506552,2.171137,...,NaN,0,0,0,0,0,0,0,0,0
9,\n\t\t\t\tcuttings\n\t\t\t,1500.0,1530.0,\n\t\t\t\t2013-11-11T03:35:04.000Z\n\t\t\t,0.007794,0.003916,0.004318,40566.284640,10469.506552,2.171137,...,\n\n\t\t\t\t\t2772\n\t\t\t\t\n\n\t\t\t\t\t2813...,0,0,0,0,0,0,0,0,0

In [88]:
df['ropAv']=df['ropAv']*3600

In [90]:
groups = df.groupby(df['ropAv']>10)

In [91]:
type(groups)

pandas.core.groupby.generic.DataFrameGroupBy

In [92]:
groups.get_group(True).head()

,typeLithology,mdTop,mdBottom,dTim,ropAv,ropMn,ropMx,wobAv,tqAv,rpmAv,...,mudGas,sourceName,dTimCreation,dTimLastChange,itemState,priv_userLastChange,priv_ipLastChange,priv_userOwner,priv_ipOwner,priv_dTimReceived
0,\n\t\t\t\tinterpreted\n\t\t\t,1380.1,1410.0,\n\t\t\t\t2013-11-10T22:49:01.000Z\n\t\t\t,19.307081,0.000400,0.001667,79490.036395,11037.087490,1.421590,...,0,0,0,0,0,0,0,0,0,0
1,\n\t\t\t\tcuttings\n\t\t\t,1410.0,1440.0,\n\t\t\t\t2013-11-10T22:49:01.000Z\n\t\t\t,28.790810,0.001624,0.002659,49199.723551,10937.664001,1.999623,...,\n\n\t\t\t\t\t2066\n\t\t\t\t\n\n\t\t\t\t\t2078...,0,0,0,0,0,0,0,0,0
3,\n\t\t\t\tinterpreted\n\t\t\t,1410.0,1440.0,\n\t\t\t\t2013-11-11T02:57:30.000Z\n\t\t\t,28.790810,0.001624,0.002659,49199.723551,10937.664001,1.999623,...,NaN,0,0,0,0,0,0,0,0,0
4,\n\t\t\t\tinterpreted\n\t\t\t,1440.0,1460.0,\n\t\t\t\t2013-11-14T03:54:59.000Z\n\t\t\t,28.101236,0.002668,0.003152,33501.490523,10582.888750,1.936630,...,NaN,0,0,0,0,0,0,0,0,0
5,\n\t\t\t\tcuttings\n\t\t\t,1440.0,1470.0,\n\t\t\t\t2013-11-11T02:11:47.000Z\n\t\t\t,29.192465,0.002668,0.003398,36392.208335,10908.709126,1.958701,...,\n\n\t\t\t\t\t2223\n\t\t\t\t\n\n\t\t\t\t\t4317...,0,0,0,0,0,0,0,0,0

In [93]:
type(groups.get_group(True))

pandas.core.frame.DataFrame

In [94]:
groups.get_group(False).head()

,typeLithology,mdTop,mdBottom,dTim,ropAv,ropMn,ropMx,wobAv,tqAv,rpmAv,...,mudGas,sourceName,dTimCreation,dTimLastChange,itemState,priv_userLastChange,priv_ipLastChange,priv_userOwner,priv_ipOwner,priv_dTimReceived
2,\n\t\t\t\tcuttings\n\t\t\t,1410.0,1410.0,\n\t\t\t\t2013-11-28T22:05:13.000Z\n\t\t\t,NaN,NaN,NaN,NaN,NaN,NaN,...,\n\n\t\t\t\t\t2478\n\t\t\t\t\n\n\t\t\t\t\t2522...,0,0,0,0,0,0,0,0,0
79,\n\t\t\t\tinterpreted\n\t\t\t,2177.4,2178.7,\n\t\t\t\t2013-12-01T21:20:54.000Z\n\t\t\t,7.258049,0.007088,0.007117,130959.57250,19106.99600,2.281015,...,NaN,0,0,0,0,0,0,0,0,0
119,\n\t\t\t\tinterpreted\n\t\t\t,2387.0,2388.3,\n\t\t\t\t2013-12-01T20:19:43.000Z\n\t\t\t,4.489344,0.006774,0.006884,142062.03200,19451.80600,1.697623,...,NaN,0,0,0,0,0,0,0,0,0
126,\n\t\t\t\tinterpreted\n\t\t\t,2420.2,2421.3,\n\t\t\t\t2013-12-01T20:20:26.000Z\n\t\t\t,5.820936,0.006558,0.006584,128917.69750,20921.20950,1.763420,...,NaN,0,0,0,0,0,0,0,0,0
128,\n\t\t\t\tcuttings\n\t\t\t,2430.0,2460.0,\n\t\t\t\t2013-11-16T13:01:06.000Z\n\t\t\t,7.917852,0.005987,0.006542,122432.33119,20976.48349,1.919658,...,\n\n\t\t\t\t\t1057\n\t\t\t\t\n\n\t\t\t\t\t1142...,0,0,0,0,0,0,0,0,0